### ISSUE TITLE
Feature Request: Shared Uniforms Across Shaders

### ISSUE THREAD

**Issue by Wyatt-James** [fincs/picasso#31]
#### Overview:
This change will enable programmers to configure the uniform-to-register mapping across shaders in a deterministic matter (and constants, as they are internally handled as uniforms).

#### Smaller Details: 
- As Picasso operates on shaders individually, the only sane way to handle this would be to allow the manual selection of registers for each uniform, and this could be done in a manner identical to the .in and .out directives.
- Uniform arrays would require the specification of the starting register, and, as they are contiguous, would be inferred from there.
- Register collisions would have to be detected.
- No changes to the DVLB would be required.
- Existing shader code would be fully compatible and its behavior unmodified.
- A multi-pass evaluation may be required to ensure that all manually-allocated uniforms are reserved before any automatically-allocated ones are.

#### Nature of Request:
- Addition
  - Extend all uniform-allocating directives to support specifying their first register.

### Why would this feature be useful?
Each shader uniform maps to one or more consecutive registers. When switching between multiple shaders which share a basic set of uniforms (i.e. the projection matrix), re-sending these uniforms on each shader swap is redundant, and can be moderately expensive and complicated. This also applies to constants, as they are treated as uniforms internally.

The ability to guarantee that shared uniforms and constants occupy the same registers across shaders in Picasso would allow programmers to avoid this redundancy, improving performance and simplifying rendering code.

According to my own research of both LibCTRU and Citro3D, I believe this behavior to be possible at a hardware level.

**Comment by fincs** [comment]
picasso already assigns the same uniform locations to uniforms of the same name present in different DVLEs within the same binary (shbin/DVLP). Please note that binding shaders sourced from different binaries involves reuploading the entire shader binary to the GPU; programmers are instead advised to bundle all shaders together in a single binary. Is that insufficient for your use case?

**Comment by Wyatt-James** [comment]
After looking more at the manual and at LibCTRU/Citro3D, it appears that I misread the manual, and I think that your suggestion may be what I'm looking for. Do you have any examples of how to do this properly? I don't see anything that uses multiple vertex shader files in the [devkitPro/3ds-examples](https://github.com/devkitPro/3ds-examples) repo.

If you would like to see my current use case, you can refer to [this](https://github.com/Wyatt-James/sm64-3ds-port/tree/cleanup-and-optimization) fork of the SM64 3DS port, specifically in regards to `src/pc/gfx/shaders,` `src/pc/gfx/gfx_3ds_shaders.c and .h,` and `src/pc/gfx/gfx_citro3d.c.` Make sure you are looking at the `cleanup-and-optimization` branch.

**Comment by Wyatt-James** [comment]
Closing as, after sorting out implementation, this does exactly what I was looking for.
