### ISSUE TITLE
Is there a problem using 2 input registers as sources for some operations?

### ISSUE THREAD

**Issue by DiscostewSM** [fincs/picasso#6]
Two methods that should result the same, yet they don't. The former seems to not work, yet the latter does.

add r0, v3, -v1   <----
mov r1, v1
add r2, v1, r0

-----------------

mov r3, v1
mov r4, v3

add r0, r4, -r3   <-----
mov r1, v1
add r2, v1, r0

I know these methods clearly aren't special, and that simple MOVs for each would make the result in less instructions, but this was for initial testing purposes of range of 0.0 to 1.0, as I attempted to use MAD with a fraction to get a value between two input registers (the fraction also part of an input register), yet my results from using 2 input registers as sources (rather than at least 1 temporary) in an ADD operation were not creating results that should have been. 

Just wondering if this is a limitation to the 3DS shader code, or if this is a bug in this shader compiler.

**Comment by fincs** [comment]
There are several hardware errata that are still being discovered. This one is one of them, i.e. two different input registers (vN) cannot be used as the two source operands of an instruction; therefore you need to use a temporary register (rN). MAD also suffers a similar erratum. Probably a future version of picasso will have warnings for these errata.

**Comment by DiscostewSM** [comment]
Ok, I'll have to work around it for the time being with temporary registers in these cases. Thanks.
